# ========== Supabase 接続情報 ==========
[supabase]
url = "https://wpxewebmezghoulnasre.supabase.co"
key = "sb_publishable_vbsGB-fQX0DLJ8oFTsCQtw_EySM-HFp"

# ========== アプリのパスワード ==========
app_password = "kennel1122"
