-- ============================================
-- Budibase / Supabase migration Phase 1
-- Source of truth (human-facing): inventory/supabase_phase1_additive.sql
-- This file exists so Supabase CLI db push can apply the same schema changes.
-- ============================================

ALTER TABLE public.products
    ADD COLUMN IF NOT EXISTS product_group TEXT,
    ADD COLUMN IF NOT EXISTS brand TEXT,
    ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;

CREATE INDEX IF NOT EXISTS idx_products_product_name
    ON public.products (product_name);

CREATE INDEX IF NOT EXISTS idx_products_is_active
    ON public.products (is_active);

CREATE TABLE IF NOT EXISTS public.product_aliases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alias_name TEXT NOT NULL,
    product_id INTEGER NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    source_system TEXT NOT NULL DEFAULT 'pos',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_product_aliases_alias_source_unique
    ON public.product_aliases (alias_name, source_system);

CREATE INDEX IF NOT EXISTS idx_product_aliases_product_id
    ON public.product_aliases (product_id);

CREATE INDEX IF NOT EXISTS idx_product_aliases_lookup
    ON public.product_aliases (alias_name, source_system, is_active);

ALTER TABLE public.product_aliases ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_policies
        WHERE schemaname = 'public'
          AND tablename = 'product_aliases'
          AND policyname = 'Allow all access to product_aliases'
    ) THEN
        CREATE POLICY "Allow all access to product_aliases"
            ON public.product_aliases
            FOR ALL
            USING (TRUE)
            WITH CHECK (TRUE);
    END IF;
END $$;

ALTER TABLE public.customer_orders
    ADD COLUMN IF NOT EXISTS order_no TEXT,
    ADD COLUMN IF NOT EXISTS store_id INTEGER,
    ADD COLUMN IF NOT EXISTS product_id INTEGER,
    ADD COLUMN IF NOT EXISTS jan_code TEXT,
    ADD COLUMN IF NOT EXISTS quantity INTEGER,
    ADD COLUMN IF NOT EXISTS unit_price NUMERIC(12, 2),
    ADD COLUMN IF NOT EXISTS order_date DATE,
    ADD COLUMN IF NOT EXISTS expected_arrival_date DATE,
    ADD COLUMN IF NOT EXISTS pickup_due_date DATE;

ALTER TABLE public.customer_orders
    ALTER COLUMN quantity SET DEFAULT 1;

UPDATE public.customer_orders
SET quantity = 1
WHERE quantity IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_customer_orders_order_no_unique
    ON public.customer_orders (order_no)
    WHERE order_no IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_customer_orders_status
    ON public.customer_orders (status);

CREATE INDEX IF NOT EXISTS idx_customer_orders_store_status
    ON public.customer_orders (store_id, status);

CREATE INDEX IF NOT EXISTS idx_customer_orders_product_id
    ON public.customer_orders (product_id);

CREATE INDEX IF NOT EXISTS idx_customer_orders_order_date
    ON public.customer_orders (order_date);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'customer_orders_store_id_fkey'
          AND conrelid = 'public.customer_orders'::regclass
    ) THEN
        ALTER TABLE public.customer_orders
            ADD CONSTRAINT customer_orders_store_id_fkey
            FOREIGN KEY (store_id)
            REFERENCES public.stores(id);
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'customer_orders_product_id_fkey'
          AND conrelid = 'public.customer_orders'::regclass
    ) THEN
        ALTER TABLE public.customer_orders
            ADD CONSTRAINT customer_orders_product_id_fkey
            FOREIGN KEY (product_id)
            REFERENCES public.products(id);
    END IF;
END $$;

CREATE OR REPLACE VIEW public.sales_enriched_v AS
WITH source_rows AS (
    SELECT
        s.id AS sales_row_id,
        s.transaction_date,
        s.transaction_date AS sale_date,
        s.store_name,
        s.product_name,
        COALESCE(s.quantity, 0) AS quantity,
        COALESCE(s.total_amount, 0)::NUMERIC(12, 2) AS total_amount,
        COALESCE(s.total_amount, 0)::NUMERIC(12, 2) AS sales_amount,
        s.created_at
    FROM public.product_sales_data s
),
matched AS (
    SELECT
        sr.*,
        alias_match.product_id AS alias_product_id,
        direct_match.id AS direct_product_id
    FROM source_rows sr
    LEFT JOIN LATERAL (
        SELECT pa.product_id
        FROM public.product_aliases pa
        WHERE pa.alias_name = sr.product_name
          AND pa.source_system = 'pos'
          AND pa.is_active = TRUE
        ORDER BY pa.updated_at DESC NULLS LAST, pa.id DESC
        LIMIT 1
    ) alias_match ON TRUE
    LEFT JOIN LATERAL (
        SELECT p.id
        FROM public.products p
        WHERE p.product_name = sr.product_name
        ORDER BY p.updated_at DESC NULLS LAST, p.id DESC
        LIMIT 1
    ) direct_match ON TRUE
)
SELECT
    m.sales_row_id,
    m.transaction_date,
    m.sale_date,
    m.store_name,
    m.product_name,
    m.quantity,
    m.total_amount,
    m.sales_amount,
    p.id AS matched_product_id,
    p.jan_code,
    COALESCE(p.category, '未分類') AS category,
    p.product_group,
    p.brand,
    p.cost_price::NUMERIC(12, 2) AS cost_price,
    p.selling_price::NUMERIC(12, 2) AS selling_price,
    (COALESCE(p.cost_price, 0) * m.quantity)::NUMERIC(12, 2) AS estimated_cost,
    (
        m.sales_amount
        - (COALESCE(p.cost_price, 0) * m.quantity)
    )::NUMERIC(12, 2) AS estimated_profit,
    CASE
        WHEN m.alias_product_id IS NOT NULL THEN 'alias'
        WHEN m.direct_product_id IS NOT NULL THEN 'direct_name'
        ELSE 'unmatched'
    END AS match_source,
    (COALESCE(m.alias_product_id, m.direct_product_id) IS NULL) AS unmatched_master,
    m.created_at
FROM matched m
LEFT JOIN public.products p
    ON p.id = COALESCE(m.alias_product_id, m.direct_product_id);

CREATE OR REPLACE VIEW public.sales_daily_summary_v AS
SELECT
    sale_date,
    transaction_date,
    store_name,
    SUM(quantity) AS total_quantity,
    SUM(sales_amount)::NUMERIC(12, 2) AS total_sales_amount,
    COUNT(*) AS line_count,
    COUNT(DISTINCT product_name) AS product_count,
    SUM(estimated_cost)::NUMERIC(12, 2) AS estimated_cost,
    SUM(estimated_profit)::NUMERIC(12, 2) AS estimated_profit
FROM public.sales_enriched_v
GROUP BY sale_date, transaction_date, store_name;

CREATE OR REPLACE VIEW public.sales_product_summary_v AS
SELECT
    sale_date,
    transaction_date,
    store_name,
    matched_product_id AS product_id,
    COALESCE(jan_code, '-') AS jan_code,
    product_name,
    COALESCE(category, '未分類') AS category,
    product_group,
    brand,
    SUM(quantity) AS total_quantity,
    SUM(sales_amount)::NUMERIC(12, 2) AS total_sales_amount,
    SUM(estimated_cost)::NUMERIC(12, 2) AS estimated_cost,
    SUM(estimated_profit)::NUMERIC(12, 2) AS estimated_profit,
    BOOL_OR(unmatched_master) AS unmatched_master
FROM public.sales_enriched_v
GROUP BY
    sale_date,
    transaction_date,
    store_name,
    matched_product_id,
    COALESCE(jan_code, '-'),
    product_name,
    COALESCE(category, '未分類'),
    product_group,
    brand;
